### ISSUE TITLE
Make override of icon colors conditional?

### ISSUE THREAD

**Issue by jonasws** [trevordmiller/nova-atom-ui#15]
I am using your theme with the [seti-icons](https://github.com/wyze/atom-seti-icons) package, and after digging around your code for a bit (along with reading the history of issues opened and closed) I discovered that you put [this in](https://github.com/trevordmiller/nova-atom-ui/blob/master/styles/overrides.less#L143), which just "throws away" any styles that would originally be applied to icons by other packages.

Is there a better way to solve this? I'm sure there are others out there with the same use case. I read that you are planning to add support sometime for colorizing icons, but IMHO it should be possible to allow this to be controlled by another package, without having to maintain a fork.

For the time being, I'm running a fork of your theme, where I've simply removed the `!important` modifier of the mentioned part of the code.

Can we have a dialog on this?

**Comment by trevordmiller** [comment]
Thank you for your feedback. The icon plugins that set colors do not align with Nova's color meanings (each color has a specific meaning as you can read about [on the website](http://www.trevordmiller.com/nova/)). If you don't care about the color meanings, I would suggest using a different color scheme as Nova is built around the color meanings.

**Comment by jonasws** [comment]
I understand. Hopefully you'll add support for nova-colors on the icons at a later stage. Keep up the good work :wink:

**Comment by trevordmiller** [comment]
@jonasws As I see it, with the color meanings defined by Nova, if a user has file icons they already use nova-colors (`trivial` if no git status, `user_current_state` if selected/hover, `user_action_needed` if destructive git modification etc.) so this is how I plan to keep it :) Thanks for your feedback.

**Comment by jonasws** [comment]
Can you elaborate a bit on that last comment (I was a little lost :confused:) ? There is not much styling of the icons with the current state of the package. Have I missed something in the documentation? I totally agree with what you're saying on colors of file icons, but is this something one would put in the `index.less` file, or should this feature be part of this theme?

**Comment by trevordmiller** [comment]
@jonasws I consider the color meanings as the most important thing in Nova so that is why I override the icon colors. Here are the color meanings I'm referring to:

![image](https://cloud.githubusercontent.com/assets/5497885/18810280/93960bb6-824f-11e6-85e1-74a4ad35b3c8.png)
![image](https://cloud.githubusercontent.com/assets/5497885/18810282/98615128-824f-11e6-843e-699c502cbaf2.png)

So, here are a few examples

![image](https://cloud.githubusercontent.com/assets/5497885/18810332/d248abd8-8250-11e6-99df-5925c9eeeea1.png)

Make sense?

If you like having branding-specific icon colors, I'd suggest using another theme that doesn't apply meanings to colors :)

Thanks for your feedback and using Nova!

**Comment by jonasws** [comment]
That was really helpful. I understand now why you made the decision to override the icon colors. I kinda like specific color-icons, and I like the color scheme proposed here. I simply thought you just hadn't gotten around to implementing it (from my experience many sages  `!important` are "shortcuts" or "hacks", but you seem to have it all figured out. Great!

**Comment by trevordmiller** [comment]
Thanks @jonasws :)
