### ISSUE TITLE
Some minor accessibility issues

### ISSUE THREAD

**Issue by brandonlilly** [trevordmiller/nova-atom-ui#16]
I really enjoy the aesthetic of nova, but there are a couple things that make me hesitate to switch from One Dark:

- [ ] No indication that tree-view vs editor-view(?) is focused (what ctrl+0 toggles between).
- [ ] Highlighting folder in tree-view highlights all subfiles. Perhaps this was a stylistic choice and I just need to get used to it. Weirdly this doesn't seem to happen in "hidden" folders, like `.git`.
- [ ] Low contrast in inactive tabs. I find it hard to read what other tabs I have open:
  <img width="460" alt="screen shot 2016-09-25 at 5 35 02 pm" src="https://cloud.githubusercontent.com/assets/9450681/18819479/6f03c80e-8346-11e6-903f-f6de955eeb8e.png">
- [ ] No differentiation between new and changed lines/files for git diffs. In One Dark it shows yellow and green for changes and new lines/files respectively (in Nova they're both just blue). Also in nova the entire folder has a left border when there are diffs within it, which I find distracting:
<img width="525" alt="screen shot 2016-09-25 at 5 53 12 pm" src="https://cloud.githubusercontent.com/assets/9450681/18819636/3d61c46a-8349-11e6-82e0-d4379817af44.png">
<img width="512" alt="screen shot 2016-09-25 at 5 52 37 pm" src="https://cloud.githubusercontent.com/assets/9450681/18819635/3d617e38-8349-11e6-9567-dbfc77153bec.png">

**Comment by trevordmiller** [comment]
@brandonlilly Thanks for using Nova and for your feedback! 
- For tree-view vs editor-view, I've created https://github.com/trevordmiller/nova-atom-ui/issues/17. for this
- For highlighting folder highlights sub-files, I must be using the class names incorrectly as it looks like the default behavior in other themes is to only highlight the folder; I've created https://github.com/trevordmiller/nova-atom-ui/issues/18 for this.
- For inactive tab contrast, this was also reported by @garth in https://github.com/trevordmiller/nova-atom-ui/issues/14 so I'll change these types of "reverse" situations (inactive tabs is just one of them and it will need to be updated across all Nova plugins so I created https://github.com/trevordmiller/nova-colors/issues/21) for this.
- For git diffs (new vs changed), I am using the Nova color meanings as described on http://www.trevordmiller.com/nova/; I'd be open to using the user action required (`nova.red`) for modifications as these are technically destructive (user action required), but currently I'm reserving that for other more destructive types of git diffs (renames + deletions) [as you can see in the syntax Atom theme](https://github.com/trevordmiller/nova-atom-syntax/blob/master/styles/syntax-variables.less#L31-L34).
- For the diff border on modified folders/files, I did this so that I could show both types of user state on a file/folder (git diff + selected); I could only change the file/folder name for git status and use a tinted background instead for currently selected files but this isn't consistent with all of the other instances of cyan text with selected things (for example tab names in Atom, Vim, HyperTerm). I also did this to be consistent with the left border on line changes inside the file so tree-view and file-view git diffs are the same. I haven't heard this is distracting for anyone else yet, but if I do I will consider it and make the change across all plugins.

Feel free to submit pull requests for these if you'd like. If not, I'll get to them at some point :)

**Comment by brandonlilly** [comment]
Thanks for the breakdown!

> For git diffs (new vs changed), I am using the Nova color meanings as described on http://www.trevordmiller.com/nova/; I'd be open to using the user action required (nova.red) for modifications as these are technically destructive (user action required), but currently I'm reserving that for other more destructive types of git diffs (renames + deletions) as you can see in the syntax Atom theme.

I take it adding another color to the palette is out of the question? Or reusing `Special` orange for modified? I wouldn't be opposed to `nova.red` either, since I don't think the destructive uses ever have a left border like that, and its a reasonable foil for the blue.

> I also did this to be consistent with the left border on line changes inside the file so tree-view and file-view git diffs are the same. I haven't heard this is distracting for anyone else yet, but if I do I will consider it and make the change across all plugins.

Using a left border as an indicator for files is perfectly fine. My qualm was about that border spans all of the subfiles too. See in my ss above, the left border is extends along the entire open `foo` folder, instead of just on the `foo`. This seems related to my second bullet where the entire folders are highlighted.

**Comment by trevordmiller** [comment]
@brandonlilly I'll consider changing the git modified status. I'll update https://github.com/trevordmiller/nova-atom-ui/issues/18 to also only add the border to the parent element.
