### ISSUE TITLE
Find pane doesn't show highlighted text

### ISSUE THREAD

**Issue by callummr** [trevordmiller/nova-atom-ui#20]
When highlighting text in the Find pane there's no indication of what's selected and what isn't.
In the screenshot below I've selected the second word - `highlighted` - and not the first word - `notHighlighted`. As you can see there's no visual indication of this.

![image](https://cloud.githubusercontent.com/assets/3995499/18826906/b80817cc-83c7-11e6-80dd-ca7a6cd78f92.png)

Running Max OS X El Capitan, Atom 1.10.2, latest Nova UI and Syntax themes.

**Comment by trevordmiller** [comment]
@callummr Thanks for the feedback! I agree. Feel free to submit a pull request [using the "CONTRIBUTING" guidelines](https://trevordmiller.github.io/nova); otherwise, I'll get to this at some point :)

**Comment by callummr** [comment]
@trevordmiller sounds like a good excuse to get in to Atom dev. Will see if I have time shortly!

**Comment by trevordmiller** [comment]
@callummr No problem. It's not too bad if you know CSS:

- Fork and clone the repo
- Create a branch
- Run `npm start` which will open a development version of Atom with live-reload enabled and linked to your local changes
- In another editor window, make changes to `/styles` and they will live-reload in the dev Atom window
- you can inspect Atom itself like you would any website in your browser and then add the related class names and rules in the `overrides.less` file: https://github.com/trevordmiller/nova-atom-ui/blob/master/styles/overrides.less
- Once the issue is fixed, run `git add -A && git commit -m "Fix find pane highlighted text (resolve #20)"`
- Submit the pull request
- I'll review and merge and then publish the update to apm and users will get it!

Let me know if you need any help. I'm happy to take care of this as well but would love your help if you are willing :)
