### ISSUE TITLE
My wrap guide line, showing max line length of 80, disappears

### ISSUE THREAD

**Issue by ctrlplusb** [trevordmiller/nova-atom-ui#21]
Comes back to life when I switch to another theme.

https://atom.io/packages/wrap-guide

**Comment by ctrlplusb** [comment]
It exists in the editor, I just can't figure out which of your styles is hiding it.

**Comment by trevordmiller** [comment]
@ctrlplusb The cursor guide is the same color as the background (novaColors.normal.black) so it doesn't show. My mistake. We can update the guide to be novaColors.decoration.medium; feel free to submit a pull request (see the contributing guidelines on https://trevordmiller.github.io/nova); otherwise I'll get to it :)

**Comment by ctrlplusb** [comment]
No problem. Would you mind doing it? I'm not looking for credit or anything. :) Will probs be faster if you punt it through.  It's a fantastic theme btw. Solid work.

**Comment by trevordmiller** [comment]
Yeah I'll get to it in priority order :)
