### ISSUE TITLE
selected background color makes some text invisible

### ISSUE THREAD

**Issue by menzer** [trevordmiller/nova-atom-ui#24]
The `.btn.selected` background-color and `.text-success` color are the same, making some text unreadable in cases like the atom-typescript package:

<img width="1181" alt="screenshot 2016-09-28 10 38 30" src="https://cloud.githubusercontent.com/assets/938511/18925258/238e7148-8568-11e6-8c3b-2f879881d042.png">

**Comment by trevordmiller** [comment]
Thanks for the feedback! I agree. I like having both the button selected and text success colors as is, but when they are combined we should override the text color with `normal.black`. Feel free to submit a pull request [using the "CONTRIBUTING" guidelines](https://trevordmiller.github.io/nova); otherwise, I'll get to this :)
